### ISSUE TITLE
Error in download() function

### ISSUE THREAD

**Issue by le717** [phoemur/wgetter#1]
Using latest 0.5.1 release.

```
wgetter.download(zipLink)
File "../wgetter\wgetter.py", line 331, in download
 reporthook(bytes_so_far, total_size, speed, eta)
File "../wgetter\wgetter.py", line 222, in report_unknown
 if bytes_so_far >= total_size:
TypeError: unorderable types: int() >= str()
```

BTW, thanks for updating this module. It really like it. :)

**Comment by le717** [comment]
@phoemur Why did you close this? This is a valid bug, still present in the code base. I just tried it again, with the same results.

```
C:\Users\le717>pip install wgetter
Downloading/unpacking wgetter
  Downloading wgetter-0.5.1.tar.gz
  Running setup.py (path:C:\Users\le717\AppData\Local\Temp\pip_build_le717\wgett
er\setup.py) egg_info for package wgetter

Installing collected packages: wgetter
  Running setup.py install for wgetter

Successfully installed wgetter
Cleaning up...
```

``` python
import wgetter
filename = wgetter.download("https://github.com/phoemur/wgetter/archive/master.zip", outdir="C:/tmp")
Downloading: 4.0KiB / Unknown - 0.0KiB/s

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    filename = wgetter.download("https://github.com/phoemur/wgetter/archive/master.zip", outdir="C:/tmp")
  File "C:\Python34\lib\site-packages\wgetter.py", line 331, in download
    reporthook(bytes_so_far, total_size, speed, eta)
  File "C:\Python34\lib\site-packages\wgetter.py", line 222, in report_unknown
    if bytes_so_far >= total_size:
TypeError: unorderable types: int() >= str()
>>> 
```

**Comment by phoemur** [comment]
updated on github and pypi, apparently i've not commited the changes, but now OK

**Comment by le717** [comment]
Yup, indeed it works now. Thanks! :smile:
